### ISSUE TITLE
How to use on Mac

### ISSUE THREAD

**Issue by shlomiLan** [mikehoyio/atom-python-black#3]
I'm using a Mac so the default Python version is 2.7 so I can't install black on it. I'm using Virtual vnev and there I installed black, but then I get the following error:

`Failed to spawn command black. Make sure black is installed and on your PATH`

This is my setup:
**Atom**: 1.28.0 x64
**Electron**: 2.0.3
**OS**: Mac OS X 10.13.5
**Thrown From**: [python-black](https://github.com/mikehoyio/atom-python-black) package 0.3.0

**Comment by mikehoyio** [comment]
Hi,

Since black requires Python 3.6.0+ you must have a Python 3 install and use the pip associated with that.

I personally have black installed via the homebrew version of Python 3.

`brew install python3
pip3 install black`

If you wish to use a version of black that you have installed into a virtualenv you must first activate that virtualenv and then launch atom. You could probably wrap this in a shell script, something like"

` #!/bin/bash
source path/to/virtualenv
atom`

**Comment by shlomiLan** [comment]
Thakns, that fixed it.
